
import { QuizQuestion, DragItem, DropTarget, TimelineEventData, Hotspot } from './types';

// Full text from user prompt for Chapter 1
const chapter1FullText = `El desarrollo histórico del trato de Dios con su pueblo del Antiguo Testamento es en sí mismo una verdad emocionante. Especialmente cuando nos damos cuenta de que la historia del pueblo de Dios que se desarrolla en la Palabra de Dios es también nuestra propia historia, si hemos creído en el Señor. Nosotros somos también pueblo de Dios. Lo que él le dijo a su pueblo hace miles de años tiene ciertamente una gran significación para nosotros hoy en día, porque Dios nunca cambia, y la necesidad que de Él tiene su pueblo tampoco cambiará jamás. Ni cambiará tampoco la naturaleza humana, a no ser por la gracia de Dios. En realidad, la revelación del Antiguo Testamento es la narración de cómo Dios ha cambiado a una muchedumbre de pecadores, transformándolos en propiedad suya, escogida entre los pueblos de la tierra. Puesto que esa labor comenzada en el Edén continúa hoy en día, la nube de testigos de los milenios pasados tiene mucho que decirnos a los de hoy.
El libro del Génesis nos habla sobre los orígenes del pueblo de Dios sobre la tierra. Nos cuenta sobre el propósito creador de Dios, y cómo creó ordenadamente todas las cosas, buenas y para su gloria. En Él se recoge la entrada del pecado en la vida del hombre, junto con la consiguiente pérdida de su amistad con Dios, que a su vez lo condujo al sufrimiento y al juicio. La crónica de la perversión del hombre que trajo como consecuencia el juicio terrible del diluvio da testimonio de la necesidad que el hombre tiene de Dios y de su gracia y salvación. Así, la idea de Dios como Salvador, que proporciona esperanza a través de su gracia, se convierte en una de las grandes doctrinas del Génesis y de toda la Palabra de Dios.
A través de todo el Antiguo Testamento podemos seguir una de las señales distintivas de los hijos de Dios, a saber, aquella sensación de necesidad de él. Vemos así cómo Jacob, Moisés, David, y Ezequías, entre muchos otros fieles, aprenden a confiar en Dios por encima de todo, y a buscar en él las respuestas a todas las perplejidades y pruebas de la vida.
Este es el pueblo de Dios, cuyos miembros son llamados uno a uno a pertenecer a la familia de Dios, y señalados por su fe en él. Así es como Dios llama a los que han de ser suyos, y este llamado aparece por vez primera en el Génesis.
Abraham, Isaac, Jacob, Judá, y sus hermanos, son todos llamados a la fe en Dios. También vemos cómo la fe que ha entrado por la gracia de Dios en los corazones de los miembros de su pueblo crece en cada uno de ellos. En ninguna otra parte del Antiguo o del Nuevo Testamento ofrece la Escritura una visión más clara del crecimiento de la fe en un hombre que cuando presenta el crecimiento de la fe de Abraham.
Al mismo tiempo vemos cómo se va desarrollando otra cualidad esencial del pueblo de Dios. El amor nace y crece en los que por naturaleza eran pecadores hostiles luego que la gracia de Dios efectúa su obra en sus corazones. Y así vemos a la familia de Jacob, egoísta y beligerante, unirse más profundamente con lazos de amor a través de las dificultades y las pruebas. Lo notamos de manera especial en dos hombres del Génesis, Judá y José.
Además de la fe y el amor, otra marcada característica de los hijos de Dios que se ve con frecuencia cada vez mayor en la Escritura es la esperanza. Esta esperanza le llega al pueblo de Dios, especialmente a Abraham y a sus hijos, a través de las promesas de Dios. Dichas promesas abarcan principalmente dos grandes esperanzas: la esperanza de una simiente (una multitud de descendientes), y la esperanza de una herencia (un lugar permanente donde vivir en la presencia de Dios).
En el Antiguo Testamento; vemos cómo se desarrollan ambos conceptos. La promesa de una simiente, dada por primera vez en Génesis 3.15, donde es llamada «la simiente de la mujer», es renovada posteriormente a Abraham. Se le da un hijo, Isaac, a través del cual se canalizan todas las promesas de Dios. Se le asegura que esa descendencia terminará convirtiéndose en una multitud. Y, como señala el Nuevo Testamento, la simiente prometida a Abraham culmina en una persona: el Cristo (Gá 3.16) .
De igual manera, la herencia prometida primeramente a Abraham es la tierra de Canaán, tierra de promisión donde habrá de habitar su descendencia. En la época de Josué la posesión se convierte en una realidad, y en la de David, mil años después de Abraham, crece hasta alcanzar desde el río de Egipto hasta el Eufrates. Sin embargo, Israel a causa de su pecado, no es capaz de retener su posesión, y el imperio se va hundiendo, hasta que la misma Jerusalén cae en manos del enemigo.
En los días de la decadencia en particular el Señor comienza a mostrarles un nuevo concepto, la esperanza de un nuevo cielo y una nueva tierra, de una nueva Jerusalén. Ahora los ojos del pueblo de Dios se levantan para esperar una herencia que no se desvanecerá, y hacia esa misma esperanza sigue señalando el Nuevo Testamento (1 P 1.3,4; Ap 21 y 22). Aunque la llamamos «esperanza nueva», el escritor de la Epístola a los Hebreos aclara bien que aun Abraham llevó consigo esta elevada esperanza hasta su muerte, y lo mismo sucedió con los demás creyentes del Antiguo Testamento (Heb 11.9,10,13-16).
Es necesario añadir una última observación con respecto al pueblo de Dios cuando, en los días de Abraham, comenzó a estar consciente de su llamamiento. El propósito de Dios no era solamente derramar sus bendiciones sobre ellos sino también que se convirtieran en un pueblo santo. Debían honrarlo y glorificarlo con sus vidas, en medio de los hombres de la tierra. Para que pudieran hacer esto, Dios los llamó a vivir una vida que lo honrara a través de la obediencia a su Palabra.
Una de las expresiones más claras de este continuo deseo de Dios para su pueblo se encuentra en Génesis 18.19, donde el Señor habla del principal propósito por el cual había llamado a Abraham. Dice el Señor: «Porque yo sé que mandará a sus hijos y a su casa después de sí, que guarden el camino de Jehová, haciendo justicia y juicio, para que haga venir Jehová sobre Abraham lo que ha hablado acerca de él». Aquí vemos expresado llanamente que Dios, al escoger primero a Abraham y llamarlo, tenía la intención de que tanto él como su descendencia vivieran con una fidelidad tal que reflejaran la voluntad de Dios en sus vidas. La realización misma de las bendiciones que Dios había prometido a su pueblo dependía de si resultaba evidente en sus vidas que eran verdaderos hijos suyos.
Los términos «justicia» y «juicio» usados aquí describen a través de toda la Escritura las altas esperanzas que Dios tenía puestas en su pueblo. Nunca suavizó sus exigencias, y a través de todo el período de la revelación del Antiguo Testamento reclamó continuamente de sus hijos esta vida y estos niveles de exigencia. Profeta tras profeta midió Israel a través de esas exigencias de justicia y juicio.
Hay un momento en el que el Señor le dice a Abraham: «Anda delante de mí y sé perfecto» (Gn 17. 1). Dios nunca altera ni suaviza estas exigencias. Así vemos a Jesús decir mucho más tarde a sus discípulos: «Sed, pues, vosotros perfectos, como vuestro Padre que está en los cielos es perfecto» (Mt 5.48). No puede haber exigencia mayor para el pueblo de Dios.
Más tarde, el Señor les dijo en el monte Sinaí a los que habían salido de Egipto que ellos eran su pueblo santo. Inmediatamente después de esta declaración, que está en el capítulo 19 del Éxodo, en el siguiente capítulo, el 20, les dio a conocer su voluntad bajo la forma de los Diez Mandamientos. Estos fueron, por tanto, dados al pueblo de Dios como expresión de la clase de vida que él quería que manifestaran al mundo.
A continuación de estas reglas específicas de conducta, que abarcan la totalidad de la voluntad revelada de Dios y que exponen más a fondo la voluntad de Dios con respecto a su pueblo, es decir, el «hacer justicia y juicio», Dios les dio un gran número de ejemplos o «juicios» que afectan a todos los aspectos de la vida. Así, siguiendo el Éxodo, en el capítulo 21 les da numerosos ejemplos tomados de la vida diaria y les enseña cómo toda faceta de su vida debe reflejar un esfuerzo conscientes por hacer la voluntad de Dios (los Diez Mandamientos).
Es aquí también donde Dios describe al pueblo los sacrificios o los medios de hacer que se dé cuenta de sus pecados y de su consiguiente necesidad del perdón divino. El pueblo no daría la talla de las altas normas establecidas por Dios. Por lo tanto, Dios les dio los sacrificios para impresionarlos con esta realidad y, al mismo tiempo, con la seriedad misma del pecado. Este debería romper el corazón de los hijos de Dios y hacerlo contrito ante él; así aprenderían a confiar en él. La totalidad del sistema sacrificial fue el medio que usó el Antiguo Testamento para humillar al pueblo de Dios y enseñarle a confiar en él. Además de todo eso, el sistema señalaba la necesidad de un salvador que pudiera rescatarlos del pecado.
El tabernáculo, introducido también en este período de la revelación, fue diseñado para mostrar al pueblo de Dios su necesidad espiritual y para llevarlo a confiar en el Salvador que Dios habría de enviarle. En sí mismo era un esquema de la obra de Cristo, como testifica posteriormente el autor de la Epístola a los Hebreos (Heb 9 y 10).
El libro del Génesis recoge también el inicio de la obra de Satanás, el gran enemigo de Dios y de su pueblo. A medida que se revelan el plan y el propósito de Dios para con su pueblo, se ve a Satanás en total oposición a los mismos y teniendo éxito cuando provoca al hombre, creado por Dios, a adoptar el mismo corazón rebelde y la misma naturaleza que él poseía. El Génesis recoge la tentación y la caída del hombre y el origen de los hijos de Satanás, los cuales continúan oponiéndose, a través de toda la historia de la redención, a Dios y a su familia, los hijos de Dios.
Satanás comienza en el Edén, pero no se detiene allí. Después de la caída, vemos a Caín, descendencia de Satanás, oponerse a Abel, quien, no obstante ser su hermano según la carne, era alguien totalmente ajeno a él en asuntos espirituales. Caín, como su padre el diablo, intenta destruir al hijo de Dios y logra matar al justo Abel, pero no puede frustrar el plan divino. Tan pronto como muere Abel, Dios hace surgir de Adán y Eva otro hijo, Set, en cuyos días, los hijos de Dios comenzaron a buscar al Señor. Es así como aparecen y se desarrollan las dos sucesiones de seres humanos en la superficie de la tierra.
Desde el punto de vista de Dios, nunca ha habido más que dos clases de hombres: los hijos de Dios y los hijos de Satanás. La trayectoria de ambos grupos puede seguirse a través de todo el Antiguo y el Nuevo Testamento, y sus respectivas categorías permanecen en realidad hasta nuestros días. Gran parte de las riquezas de la Palabra de Dios la vemos en la revelación bíblica con respecto a la naturaleza de los hijos de Dios y los hijos de Satanás, y el trato que Dios da a cada uno de ellos.
La oposición de Satanás continúa incluso después del diluvio. Así encontramos, por ejemplo, que Abraham y sus hijos se enfrentan con la continua hostilidad de la descendencia de Satanás que vive en Canaán. Más tarde, en Egipto, la malvada oposición de la simiente de Satanás en la persona del faraón y los egipcios es bien evidente. Cuando Israel sale de Egipto y se dirige de nuevo hacia Monte Sinaí Canaán, esta hostilidad de los enemigos de Dios aumenta. Toda la historia de Israel está repleta de enemigos.
Trágicamente vemos cómo los hijos de Satanás se van infiltrando gradualmente en la familia del pueblo de Dios, la iglesia del Antiguo Testamento. Pronto habrá tantos incrédulos como creyentes, o quizá aun más, en la iglesia, el cuerpo visible del pueblo de Dios. En el Antiguo Testamento las hostilidades culminan con la caída de Jerusalén y la consiguiente cautividad en Babilonia. Pero la enemistad no termina ahí. Después del regreso, encontramos a Jerusalén y a Judea llenas de enemigos del pueblo de Dios.
En los tiempos del Nuevo Testamento la iglesia se ve penetrada de nuevo por los no creyentes. Los agentes de Satanás en la iglesia, la mayoría de los judíos de la época de Jesús, se alían finalmente con el poder secular de Roma para expresar el máximo de su hostilidad con la crucifixión del mismo Jesucristo, Hijo de Dios.
El Nuevo Testamento abunda aún más con respecto a la continua hostilidad entre el pueblo de Dios y los hijos de Satanás. Esto lo vemos vivamente descrito en el capítulo doce del Apocalipsis.
Al señalar estos importantes temas en el Génesis, hemos mostrado también cómo están presentes a todo lo largo del Antiguo Testamento: la necesidad que tiene el hombre de Dios; el llamado del pueblo de Dios; la labor opositora de Satanás. La Escritura traza después la historia del trato de Dios con su pueblo en la historia de Israel. Dicha historia ha sido escrita teniendo como fondo la del mundo secular. El surgimiento y la caída de las naciones y de los grandes imperios están entretejidos en el plano posterior de la historia bíblica. La obra de Dios para redimir a su pueblo no fue algo aislado de la realidad cotidiana de la historia que se desarrollaba alrededor de Israel.
La historia del pueblo de Dios resulta ser la compilación de los éxitos y fracasos de Israel, que dependen de su mayor o menor obediencia a su Señor.
Cuando Israel heredó la tierra de Canaán, tuvo éxito y prosperó en ella solo mientras se mantuvo sujeto a la Palabra y a la voluntad de Dios. Cuando los padres comenzaron a dejar de preocuparse por instruir a sus hijos de acuerdo con el deseo expreso de Dios manifestado en Deuteronomio 6.4ss, toda la nación sufrió. Así lo leemos en el recuento de los trágicos días de los jueces.
Cuando el pueblo era quebrantado por sus enemigos, y alcanzaba el punto extremo de la desesperación, Dios hacía surgir hombres del estilo de Samuel y David, quienes le hablaban de volverse a él. Los ejemplos de caudillaje de Saúl y de David muestran el marcado contraste que existe entre un pastor del rebaño de Dios que es infiel y otro que es fiel, confrontación que es típica de toda la historia del Antiguo Testamento.
Cuando fallan los dirigentes, como sucedió en los tiempos de Salomón y sus sucesores, los trágicos resultados afectan a toda la iglesia, y todos sufren, tanto los pecadores como los santos. Tanto la descendencia de Satanás en Israel como los creyentes verdaderos sufren las consecuencias de las infidelidades de Israel.
Para contrarrestar la mala influencia de Salomón y de otros como él, que llevaron a Israel por caminos de perdición, ciertos escritores anónimos de la Palabra de Dios les hicieron resistencia escribiendo obras como el Cantar de los Cantares y el Eclesiastés. El estudio de dichos libros muestra lo devastadora que puede ser la infidelidad de los líderes para toda la iglesia.
También para contrarrestar la mala influencia de Salomón y sus malvados sucesores al trono de Israel, Dios hizo surgir una continua oleada de profetas. Estos profetas se enfrentaron valientemente a la hostilidad de la falta de fe que existía en Israel para exhortar a aquellos que confiaban en Dios a continuar siéndole fieles.
Desde Joel en el siglo noveno antes de Cristo, quien previene contra la decadencia espiritual, mientras el gozo de servir a Dios desaparece de los corazones del pueblo; a través de todo el siglo octavo, con el gran número de profetas que denuncian los pecados sociales y las injusticias de sus días; y hasta los siglos séptimo y sexto, con su deterioro espiritual, Dios envía profeta tras profeta para que llamen al pueblo al arrepentimiento y al regreso a su Señor.
Amós reprende su falta de amor mutuo, mientras que Oseas describe su falta de amor a Dios. Jonás representa la aversión de algunos de los verdaderos hijos de Dios a obedecerle y someterse a sus designios redentores para con los hombres. Jeremías enfoca la condición pecadora de los corazones en el pueblo, y señala con esperanza una solución definitiva que vendrá de parte de Dios: el cambio de corazón.
En la cautividad, profetas como Ezequiel y Daniel dan testimonio de la gracia continua de Dios y de cómo él sostiene a quienes ponen en él toda su confianza.
La doctrina del remanente, que fue presentada en el siglo octavo por los profetas Amós e Isaías, y desarrollada posteriormente por los profetas Jeremías y Ezequiel, muestra que, aunque el pueblo de Dios deberá pasar por grandes pruebas y terribles juicios, Dios preservará a todos aquellos que pongan su confianza en él. En ningún otro lugar tenemos una expresión mejor y más ferviente de esta esperanza que en el profeta Habacuc, cuyo ministerio se desarrolla en la época de la caída de Jerusalén.
El remanente del pueblo de Dios regresó de veras a su tierra. De la cautividad de Babilonia salió el gran contingente de todos aquellos que querían hacer la voluntad de Dios. Este remanente regresó a Jerusalén y reconstruyó su templo y sus muros. Esta época está marcada por un gran amor por la Palabra de Dios, y en especial por la Ley de Moisés. Es un período de reavivamiento y de regreso, o al menos, de un gran deseo de regresar a los altos niveles de exigencia que Dios había fijado para su pueblo en la Ley de Moisés.
Durante todo este tiempo, de avivamiento o decadencia espiritual del pueblo de Dios según se narra en el Antiguo Testamento, hay continuamente salmos, cantos, y proverbios que expresan la fe de los hijos de Dios que vivieron a través de todas esas épocas. Los autores de la mayoría de esos escritos nos son desconocidos. Pero puesto que han sido conservados en la Palabra de Dios, sabemos que lo que expresan, como cualquiera otra porción de las Escrituras, es Palabra de Dios.
Job manifiesta la fe de un hijo de Dios, probada en la confrontación con pruebas sumamente difíciles, pérdidas y sufrimientos. Es un testimonio de la longanimidad de Dios, comunicada a su vez a un hijo suyo, dándole fuerzas para mantenerse en su fe, aun en los momentos en que las personas más cercanas a él estaban en duda.
Los Salmos recogen en forma bella la fe de muchos de los hijos de Dios, además de David, el gran salmista. Quizá el Salmo primero es el que mejor ejemplifica el contenido de todo el libro. Presenta la justicia del pueblo de Dios, en contraste con la maldad de los que no tienen fe. Aquí, como en muchos otros lugares, el hijo de Dios se describe como un árbol trasplantado junto a corrientes de aguas de gracia y de la Palabra de Dios. Da su fruto a su tiempo y su hoja no cae. Ilustra maravillosamente la dependencia absoluta de los hijos de Dios en la Palabra y el poder sustentador de ese Dios. La pone también en fuerte contraste con la estéril vida del malvado, y su inevitable final sin esperanza y sin herencia.
Hemos esquematizado aquí solo brevemente el desarrollo del contenido del mensaje que Dios presentó a su pueblo en el Antiguo Testamento. Ello basta para demostrar la gran importancia que tiene este antiguo mensaje de Dios para su pueblo de hoy en día. La validez siempre actual de la Palabra de Dios fue elocuentemente expresada por el mismo Jesús cuando le hablaba a su propia generación. En cierta ocasión les replicó a los fariseos: «Abraham vuestro padre se gozó de que había de ver mi día, y lo vio, y se gozó.... Antes que Abraham fuese, yo soy» (Jn 8.56,58). Como afirma también el autor de la Epístola a los Hebreos: «Jesucristo es el mismo ayer, y hoy, y por los siglos» (Heb 13.8). El Cristo eterno hace que la Palabra de Dios sea siempre para el pueblo de Dios algo importante y de sabor contemporáneo.
En los capítulos siguientes, pues, haremos algo más que estudiar la vida de un pueblo antiguo y aprender cosas sobre el mismo. Vamos a estudiar la revelación que hace Dios mismo sobre su verdad y su voluntad con respecto a su pueblo, no solo el pueblo de las épocas antiguas sino el de todos los tiempos. En este estudio tenemos mucho que aprender para nuestros días y para nuestra vida cotidiana.`;

// Full text from user prompt for Chapter 2
const chapter2FullText = `I. La creación del mundo (caps. 1 y 2)
Las palabras con que comienza el Antiguo Testamento hablan de orígenes. Los orígenes de que se habla son los de la creación del cielo y de la tierra. Se presupone que Dios es alguien que ya existía antes de este principio. Las Escrituras dicen poco sobre lo que precedió a la creación del mundo y, por tanto, lo que la precedió no es esencial para el conocimiento humano.
Las Escrituras tienen dos respuestas para nuestra curiosidad sobre estas cosas: una en el Antiguo Testamento y la otra en el Nuevo. Primeramente, en el Antiguo Testamento, en Deuteronomio 29.29, Dios nos dice que las cosas secretas pertenecen al Señor, pero lo que ha sido revelado nos pertenece a nosotros y a nuestra descendencia para siempre. Esto es lo mismo que decirnos que debiéramos preocuparnos de lo que Dios ha revelado, y no ser demasiado curiosos con respecto a lo demás. Lo revelado basta para atraer toda nuestra preocupación y nuestra atención.
Sin embargo, las Escrituras sí nos revelan de manera parcial algunos aspectos concernientes al propósito creador que estaba en la mente de Dios. Este concepto del propósito de Dios en la creación es algo sumamente importante para nuestro conocimiento. Aunque a través de todas las Escrituras, este propósito divino aparece implícito, se nos enseña explícitamente en Efesios 1.4. Aquí se nos dice que Dios nos escogió en Cristo antes de la fundación del mundo, esto es, antes de la creación. Por tanto, se nos muestra cuál era el propósito de Dios: que fuésemos santos y sin mancha delante de él en amor.
Sé que algunas traducciones ponen la frase «en amor» con la oración siguiente (el original griego permite ambas construcciones). Pero dicha frase es necesaria para completar el concepto precedente, y en realidad así lo hace, por lo cual es preferible traducir así, no solo desde el punto de vista gramatical sino también porque está más de acuerdo con la verdad divina, tal como ha sido revelada a través de las Escrituras.
La enseñanza es la siguiente: Dios, antes de la creación, se hizo el propósito de llegar a tener un pueblo que pasara la eternidad con él y con el que pudiera compartir las bendiciones de toda esa eternidad. El solo pensamiento de esta realidad nos maravilla, porque se halla más allá de toda nuestra comprensión. Nos habla de un Dios de amor que por amor nos incluye en sus designios eternos. Un Dios que nos escoge específicamente a nosotros para que le acompañemos para siempre. Y se propuso realizar nuestra entrada en su familla por medio de su Hijo Jesucristo. Aquí queda implícito todo el plan de salvación, tal y como las Escrituras lo desarrollan. La cuestión realmente importante es que Dios nos escogió en Cristo antes de crear el cielo y la tierra. Así vemos cómo los propósitos fundamentales de ese Dios, afectan a todo lo que comienza a hacer cuando crea al mundo y al hombre.
A continuación, sigue una explicación sobre la clase de pueblo que Dios se proponía llegar a tener. Sus individuos deberían ser santos y sin mancha. Las dos ideas no son sinónimas. «Santo» es la palabra usada para todo lo que es apartado para Dios. Este pueblo debería ser un pueblo santo, es decir, un pueblo que fuera propiedad exclusiva de Dios. «Sin mancha» nos enseña que debería ser un pueblo sin pecado y sin defecto, ya que solo un pueblo así podría permanecer para siempre en la presencia de Dios.
Además, debería estar delante de Dios, en su presencia, en una relación de amor. Dios nos habla aquí del amor, relación esencial que debe ser el lazo que una a los miembros del pueblo de Dios, y que lo una a él con dicho pueblo. En las Escrituras se presenta frecuentemente el amor como el lazo de unión entre las Personas de la Trinidad (Jn 3.35; 15.9; 17.23,26), lo que hace que el hombre, que ha de ser creado a imagen de Dios, deba poseer también esta característica.
Efesios 1.4 nos ayuda por tanto a ver qué es lo que tenía Dios en su mente cuando comenzó a crear el cielo y la tierra y cuando puso al hombre en ella. Necesitamos este concepto para poder ver la maravillosa unidad de la Palabra de Dios cuando intentamos discernir cuáles son las motivaciones de Dios en todas sus relaciones con el hombre. El propósito inicial de Dios nunca quedará frustrado; él se mantiene firme en sus intenciones, y va llevando gradualmente sus propósitos iniciales a su perfecto cumplimiento. Esta es la maravillosa historia que se va desarrollando en la revelación de Dios, es decir, en las Escrituras del Antiguo y del Nuevo Testamento.
El primer párrafo de las Escrituras (Gn 1.1-5) presenta la labor creadora de Dios. El verbo usado aquí para la acción de «crear» es una palabra que únicamente aparece en las Escrituras teniendo a Dios por sujeto. Por tanto, quiere significar únicamente la labor divina que trae a la existencia aquello que antes no existía.
Para revelarnos aun más sobre el poder creador de Dios, se nos dice que él sacó el orden del caos, y la luz de las tinieblas (v. 2). El versículo segundo es un comentario del primero, y no una adición. Para su propia gloria, Dios creó primeramente el cielo y la tierra, pero en un estado caótico y tenebroso, y posteriormente puso el orden y la luz en lo que ya había hecho.
La palabra usada aquí para nombrar a Dios es un término genérico que en el idioma hebreo es una palabra en plural. Es correcto traducirla como un singular, puesto que el verbo hebreo «creó» está en singular. La razón por la cual el nombre de Dios está en plural es que se desea expresar la majestad de Dios, siendo además muy posible que haya sido para indicar la pluralidad de personas existente en la Divinidad. El mismo versículo presenta al Espíritu de Dios como una persona, indicando así la existencia de una pluralidad de personas en la divinidad única. Aquí se encuentra implícita la doctrina trinitaria, aunque debamos esperar al Nuevo Testamento para verla expresada en forma explícita. En otras palabras, el uso de una forma plural para mencionar a Dios, y la presentación del Espíritu de Dios como persona, tiene en cuenta, aunque no lo enseñe de manera explícita, la personalidad trinitaria de Dios.
Debemos notar que los conceptos presentados aquí, de un orden sacado del caos y de una luz sacada de las tinieblas, son usados en el Nuevo Testamento para presentarnos la obra redentora realizada por Dios en nuestras vidas. En 2 Corintios 5.17 se nos dice que si alguno está en Cristo nueva criatura es. Las cosas viejas pasaron y él es hecho nuevo. Pablo se refiere de nuevo a Génesis 1.2 en 2 Corintios 5: 17, cuando dice que Dios, que ordenó que de las tinieblas resplandeciese la luz, es el que resplandeció en nuestros corazones para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo. Aquí se nos está hablando de la obra de nuevo nacimiento o regeneración que ocurre en el corazón de todo creyente, haciéndole posible conocer a Dios y tener salvación. Así como el Espíritu estaba activo en la primera creación y en su iluminación, así también lo está en nuestra nueva creación espiritual, que nos incorpora como miembros a la familia de Dios. Juan 1.4,5 hace alusión en forma similar a la luz de Dios que estaba en los hombres, y que supera a las tinieblas.
Algo que también necesitamos dejar señalado aquí es que la secuencia de tarde y mañana (Gn 1.5) que constituye el orden bíblico del período de 24 horas, refleja una y otra vez este triunfo de la luz sobre las tinieblas. Aquí se nos muestra cómo Dios ha puesto dentro de la creación misma, y dentro del orden de noche y día, una enseñanza que nos habla de que él creó la luz para derrotar las tinieblas, y del inevitable triunfo de la luz espiritual sobre las tinieblas espirituales. La revelación natural de Dios comienza desde el mismo día primero de la creación.
Los versículos 6 y 8 hablan de la forma primitiva de la tierra en el momento de ser creada por Dios. Es importante fijarse aquí cuál es la enseñanza que se presenta. La palabra «firmamento» estaría mejor traducida si se dijera «expansión».* Hace referencia al área vital que Dios hizo para el hombre en la tierra. Había agua almacenada por encima y por debajo de esa expansión. Nos damos cuenta de que las cosas no son así en el mundo de hoy. No conocemos la existencia de tales acumulaciones de agua por encima y por debajo del área vital del hombre sobre la tierra. No existen en la actualidad. Esa es la cuestión: el mundo que Dios hizo al principio, parece haber sido diferente del que hoy conocemos. Durante el diluvio, este mundo sufrió cambios catastróficos en su totalidad, que lo hicieron convertirse en el mundo que hoy conocemos. Este era precisamente el argumento de Pedro cuando escribía a la iglesia, al final de su vida.
En 2 Pedro 3.3-7 se hace referencia a unos tiempos faltos de fe, en los cuales los hombres, desconociendo voluntariamente lo que Dios había hecho para juzgar al mundo antiguo con el diluvio, dejarían de creer en la segunda venida de Cristo. Afirmarían que, de acuerdo con sus observaciones, el mundo permanece el mismo desde el principio. Pedro insiste en el versículo 5 en que desconocerán voluntariamente la doctrina de la creación tal como aparece en el capítulo primero del Génesis. El mundo anterior al diluvio, nos dice Pedro, era muy diferente del actual. Provenía del agua. Y en el diluvio, por medio de los grandes depósitos de agua que se hallaban por encima y por debajo de la tierra, el mundo que existía entonces fue destruido. De esta forma, Pedro presenta el contraste entre aquel mundo y el cielo y la tierra actuales (v. 7).
Es importante notar que el mundo como Dios lo creó al principio era bastante diferente de cómo es hoy en día. Los grandes depósitos de agua que estaban por encima y por debajo de la tierra habitable fueron abiertos en el momento del diluvio, y en consecuencia produjeron en la tierra unos cambios tan catastróficos que alteraron radicalmente toda su estructura y su aspecto mismo. Más tarde veremos cómo el diluvio significó mucho más que una lluvia que duró cuarenta días con sus noches. Fue también la ruptura de las fuentes de los abismos y la apertura de las cataratas del cielo (Gn 7.11). La lluvia fue solamente el tercer elemento del diluvio, y probablemente resultó ser el más insignificante en cuanto a los daños producidos (Gn 7.12. Ver también Gn 8.2) .
Esta es la consistencia interna de las Escrituras. No tenemos aquí alusión a ningún concepto mitológico antiguo sobre la estructura de la tierra, sino la Palabra de Dios, claramente revelada tanto en el Antiguo como en el Nuevo Testamento, y dando testimonio de la misma realidad. Los que en el día de hoy dejan de lado la revelación bíblica en su búsqueda de la verdad sobre el mundo y sus orígenes, y que por tanto calculan la evolución de la tierra hasta su forma presente en millones o miles de millones de años, simplemente están desconociendo la obra creadora de Dios y su poder de juicio para cambiar en un momento lo que él mismo ha creado. Pasan por alto los efectos catastróficos que tuvo el diluvio sobre el mundo, en su insistencia sobre la necesidad de miles de millones de años para que en la tierra se lleguen a producir grandes cambios. Y aunque ellos puedan llegar a descubrir muchas grandes verdades sobre el universo, por las que les debemos estar agradecidos, en la interpretación de dichas realidades debemos guiarnos por la Palabra de Dios. No puedo ver cómo podría un cristiano actuar en forma diferente.
El resto del capítulo primero, dando el orden de la creación, primero la luz, después un lugar donde habitar, y posteriormente la tierra firme y las aguas para que las distintas formas de la creación viviesen en ellas, nos presenta una evidencia aun mayor del trabajo ordenado que realiza la mente de Dios. Después de esto, son hechas las lumbreras que han de iluminar al hombre. A continuación, las aguas y la tierra se llenan de toda clase de criaturas.
El versículo 26 presenta la creación del hombre, obra cumbre del Creador, en el sexto día. En todo esto vemos el orden y el plan de Dios a medida que va desarrollando su obra creadora. Esto en sí mismo presenta a Dios como un ser ordenado y lleva implícita la idea de que aun antes de comenzar la creación, ya había un propósito fijo en la mente divina, que fue el que tuvo como consecuencia la creación del hombre, para el cual había preparado ya un mundo en todo adecuado. Se describe aquí al hombre como creado a imagen de Dios. No se nos dice qué implica esta afirmación, pero posteriormente una revelación más amplia de la Palabra de Dios, nos enseña que el hombre fue creado para Dios para tener compañerismo con él. Como ya hicimos notar, en Efesios 1.4 se afirma que el hombre fue hecho para vivir ante Dios, en su presencia en amor. Esto sugiere la existencia en el hombre de capacidades similares a las que se hallan presentes en Dios mismo. Ser a la imagen de Dios, por tanto, es ser capaz de tener amistad con Dios, y de experimentar amor recíproco por él, reflejando así el amor que él nos tiene. El hombre es, pues, un ser único, puesto que reúne cualidades que no se encuentran en ninguna otra criatura conocida.
Vemos también cómo las frases «hagamos al hombre» y «nuestra imagen» implican, aunque tampoco expongan en forma explícita, una referencia a la personalidad plural de Dios. Por otra parte, Dios le da al hombre un quehacer y una responsabilidad ante él. El hombre habría de llenar y someter la tierra, ejerciendo dominio sobre todo lo que Dios había creado (1.28). Luego que Dios hubo terminado su obra creadora se sintió complacido, y declaró que todo era bueno en gran manera. Esto ciertamente lleva implícito que la creación no tenía defectos, y que el hombre, tal como fue hecho por Dios, era también bueno en gran manera (sin pecado).
Hagamos una pausa en este momento para notar que todos los factores señalados en Efesios 1.4 están presentes en el momento de la creación. Dios creó al hombre santo (es decir, para él) y sin mancha (bueno en gran manera) para vivir delante de él (en su presencia e imagen) en una relación de amor. Esto último se manifiesta en el hecho de que Dios le había dado ya al primer hombre mandamientos por los cuales este podría, a través de la obediencia, demostrarle su amor. Jesús mismo lo dijo más tarde: «Si me amáis, guardad mis mandamientos» (Jn 14.15; cf. Jn 15.14). La obediencia, por tanto, ha sido siempre una manifestación del amor que le tienen sus hijos a Dios. La situación que habría de permitir el cumplimiento del propósito de Dios al crear al hombre fue establecida desde el principio. Todos los elementos esenciales para el cumplimiento de este propósito estaban presentes y habían sido constituidos desde el momento mismo de la creación.
En el capítulo 2, versículos 1 al 3, se nos presenta la idea del Sabbath, el tiempo en que Dios descansó de su labor creadora. Esto sugiere también la intención divina de traer a su culminación todas las cosas que Dios había comenzado. Para inculcar esta verdad en el hombre se afirma expresamente aquí que Dios descansó en el séptimo día, y santificó (hizo santo) ese día.
Más tarde el escritor de la Epístola a los Hebreos nos mostrará cómo este séptimo día fue establecido de forma simbólica para indicar la entrada definitiva del pueblo de Dios en el descanso y la amistad con Dios (Heb 4.3-11). Por lo tanto, desde los tiempos de la creación cada séptimo día se nos presenta como un recordatorio del gran propósito de Dios de tener un pueblo ante él para siempre. Cada Sabbath a partir de entonces habría de recordar esta esperanza al pueblo de Dios, y era en realidad como un pequeño anticipo de eternidad en un ensayo de lo que sería el cielo mismo, ya que en dicho día, el pueblo de Dios debía dejar a un lado las labores profanas de este mundo y entregarse por completo a gozar de Dios. Más adelante veremos cómo esta doctrina se desarrolla.
En el capítulo 2, versículo 4, Dios se nos presenta en una forma personal. Su nombre propio, Yahweh, o Jehová, o el Señor, como dicen algunas traducciones, aparece aquí por vez primera. Es significativo que sea aquí, porque en los versículos siguientes se hace énfasis en que Dios cuida personalmente del hombre, satisfaciendo todas sus necesidades: físicas, emocionales, y espirituales. Mientras que el capítulo 1 ha señalado el orden de la creación, el tema principal del capítulo 2 es el hombre como obra cumbre de la creación, mostrándonos cómo en el propósito de Dios todo fue hecho para el hombre y para su bien. Es por eso que en este capítulo se hace énfasis sobre todo en el orden lógico, más que en el cronológico. El capítulo 2 nos demuestra el amor que Dios le tiene al hombre, que es hechura suya.
El versículo 5 sugiere la idea de que hace falta el hombre para completar la creación. El versículo 7 explica en detalle la creación del hombre, tanto para mostrar su humilde origen del polvo de la tierra, como su otro origen, tan encumbrado, que procede del aliento mismo de Dios.
Los versículos 8 al 14 hablan de la abundancia con que Dios satisfizo las necesidades físicas del hombre, dándole un lugar especial que pudiera considerar suyo en esta hermosa tierra, y proveyéndole de toda clase de buenos frutos para nutrir su cuerpo.
En el versículo 9 se nos dice que había dos árboles en medio del jardín. Se los presenta en forma misteriosa, sin explicar su naturaleza; solo se dice que uno es el Árbol de la Vida y el otro el Árbol de la Ciencia del Bien y el Mal.
Fuera del contexto de los capítulos 2 y 3, el segundo de los árboles no vuelve a ser mencionado. Puesto que recibe el nombre de Árbol de la Ciencia del Bien y el Mal, sin duda fue colocado allí para probar a través de la obediencia el amor que Adán le tenía a Dios. La alternativa sería: «¿Deberá el hombre conocer el bien y el mal a través de la revelación de Dios, o mediante su propia experiencia independientemente de esa revelación divina?» Su sola presencia allí en consecuencia, ponía a Adán en la obligación de escoger entre depender de la voluntad revelada de Dios o buscar la manera de existir sin depender de él. Lo primero pondría de manifiesto su amor a Dios; lo segundo, su odio.
Dios satisfizo también las necesidades emocionales del hombre. Puesto que era imagen de Dios, es obvio que el hombre había sido creado para cargar con grandes responsabilidades. Debido a ello Dios le dio una tarea que debía realizar (vv. 15-17). Asimismo, Adán recibió órdenes específicas, con cuyo cumplimiento manifiesta su amor a Dios.
Por último, Dios satisfizo la necesidad del hombre en un área especial. El hombre había sido creado para tener amistad con Dios, pero en un contexto de convivencia con hombres similares a él. Se nos dice que Dios creó al hombre varón y hembra (1.27). Aquí, en el capítulo 2, tenemos una ampliación de esta creación de la mujer, lo que nos muestra una vez más que toda la obra de Dios fue hecha pensando en el hombre y en su bien, nacida del amor de Dios para con el hombre.
Se describe aquí a la mujer como una ayuda idónea para el hombre, una respuesta a sus necesidades. Fue hecha para el hombre, y para completar al hombre. El hombre solo estaba incompleto; así es como la necesidad mutua del hombre y la mujer está hondamente marcada en la fibra misma de la humanidad.
Dios sacó a la mujer del cuerpo del hombre y ordenó que, a partir de entonces, los hombres nacieran de mujer, poniendo el acento de nuevo en una dependencia del uno respecto al otro, y en la necesidad mutua que solo el otro puede satisfacer. Sin embargo, el hombre era la obra cumbre, y en este sentido, la mujer estaba sujeta a él; no que fuera inferior, sino que le estaba sujeta.
Dios dispuso en la creación el concepto de la familia como la forma en la que llamaría a su pueblo y lo redimiría. La relación entre esposo y esposa habría de reflejar la relación eterna entre Cristo y su iglesia (Ef 5.22-33).
Concluimos esta sección, pues, haciendo de nuevo la observación de que el propósito divino, tal como se expresa en Efesios 1.4, está plenamente manifestado en el momento de la creación del hombre a imagen de Dios: tenemos aquí unos seres humanos que son santos y sin defecto ante Dios, en un estado de amor. Pero la carencia de pecado y el amor deben ser probados. Por encima de todo, debía someterse a prueba el sentido de la necesidad de Dios en Adán, si habría de haber aquel compañerismo eterno que Dios mismo había propuesto y deseado.`;

export const CHAPTER_1_TEXT = {
    intro1: "El desarrollo histórico del trato de Dios con su pueblo del Antiguo Testamento es una verdad emocionante. La historia del pueblo de Dios es también nuestra propia historia. Lo que él le dijo a su pueblo hace miles de años tiene gran significación para nosotros hoy, porque Dios nunca cambia, y la necesidad que su pueblo tiene de Él tampoco.",
    intro2: "La revelación del Antiguo Testamento narra cómo Dios ha transformado a pecadores en su propiedad escogida. El libro del Génesis nos habla sobre los orígenes, el propósito creador de Dios, la entrada del pecado y el juicio, pero también introduce la idea de Dios como Salvador, una doctrina clave en toda la Biblia.",
    quote1: "Porque yo sé que mandará a sus hijos y a su casa después de sí, que guarden el camino de Jehová, haciendo justicia y juicio, para que haga venir Jehová sobre Abraham lo que ha hablado acerca de él.",
    faith: "Una señal distintiva de los hijos de Dios es la sensación de necesidad de Él. Personajes como Jacob, Moisés y David aprendieron a confiar en Dios sobre todo. Este es el pueblo de Dios, llamado a la fe, un llamado que aparece por primera vez en Génesis con Abraham y sus descendientes. La Escritura muestra de forma clara el crecimiento de la fe de Abraham.",
    love: "El amor es otra cualidad esencial que nace y crece en los corazones transformados por la gracia de Dios. Vemos a la familia de Jacob, antes egoísta, unirse con lazos de amor a través de las pruebas. Esto es especialmente notable en Judá y José.",
    hope: "La esperanza, junto a la fe y el amor, llega al pueblo de Dios a través de sus promesas. Estas se centran en dos grandes conceptos: la promesa de una simiente (descendencia) y la de una herencia (un lugar donde vivir en la presencia de Dios).",
    promiseSeed: "La promesa de una simiente, dada por primera vez en Génesis 3:15, es renovada a Abraham. A través de su hijo Isaac, se promete una multitud de descendientes. El Nuevo Testamento señala que esta simiente prometida culmina en una persona: Cristo (Gálatas 3:16).",
    promiseInheritance: "La herencia prometida a Abraham fue la tierra de Canaán. Aunque Israel la poseyó, la perdió por su pecado. Más tarde, surge la esperanza de un nuevo cielo y una nueva tierra, una herencia eterna que los creyentes del Antiguo Testamento, como Abraham, ya anhelaban (Hebreos 11).",
    satanIntro: "El libro del Génesis también recoge el inicio de la obra de Satanás, el gran enemigo de Dios y de su pueblo. Desde el principio, se opone al plan divino, tentando al hombre a la rebelión.",
    satanConflictOrigin: "El conflicto se ve en Caín, descendencia de Satanás, oponiéndose a Abel. Aunque Abel muere, el plan de Dios no se frustra y surge Set. Así comienzan las dos líneas de la humanidad: los hijos de Dios y los hijos de Satanás, un tema central en toda la Escritura.",
    satanOpposition: "La hostilidad de Satanás continúa a través de la historia: en Canaán, en Egipto con el Faraón, y a través de los enemigos de Israel. Trágicamente, los hijos de Satanás se infiltran en el pueblo de Dios, culminando en la crucifixión de Jesús, una alianza entre los líderes religiosos y el poder de Roma.",
    fullText: chapter1FullText
};

export const CHAPTER_2_TEXT = {
    purpose: "El Antiguo Testamento comienza con los orígenes. Aunque las 'cosas secretas pertenecen al Señor' (Deuteronomio 29:29), Dios revela su propósito creador. Efesios 1:4 enseña que, antes de la creación, Dios nos escogió en Cristo para ser 'santos y sin mancha delante de él, en amor'. El propósito de Dios era formar un pueblo para compartir la eternidad con Él, un pueblo santo (apartado para Él) y sin mancha (sin pecado), unido por el lazo del amor.",
    creationWork: "Génesis 1 presenta la majestuosa y ordenada obra de Dios. El verbo 'crear' se usa exclusivamente para la acción divina de traer a la existencia lo que no existía. El uso del nombre plural para Dios ('Elohim') junto al verbo singular ('creó') sugiere la majestad y la pluralidad dentro de la Deidad, una insinuación temprana de la doctrina de la Trinidad.",
    orderFromChaos: "Dios trae orden del caos y luz de las tinieblas. Este acto no es solo físico; es un poderoso arquetipo de la obra redentora de Dios en la vida del creyente. Como dice 2 Corintios 4:6, el mismo Dios que ordenó que la luz resplandeciera de las tinieblas es el que 'resplandeció en nuestros corazones' para darnos conocimiento de Su gloria. La regeneración espiritual es una nueva creación.",
    differentWorld: "El mundo pre-diluviano, como se describe en Génesis y se alude en 2 Pedro 3, era estructuralmente diferente al nuestro, con 'aguas sobre y debajo de la expansión'. La Biblia enseña que el Diluvio no fue solo una lluvia prolongada, sino un evento cataclísmico que reconfiguró la tierra. Esto desafía las interpretaciones que descartan los cambios geológicos rápidos y se basan únicamente en procesos lentos de millones de años.",
    creationOfMan: "El hombre es la obra cumbre de la creación, hecho 'a imagen de Dios'. Esto significa que fue creado con la capacidad única de tener comunión con Dios, de amarlo y reflejar Su carácter. La frase 'hagamos al hombre' vuelve a apuntar a la pluralidad en la Deidad. Al hombre se le da la responsabilidad de ejercer dominio sobre la creación, y al terminar, Dios declara que todo era 'bueno en gran manera'.",
    personalCare: "Mientras Génesis 1 muestra el orden cronológico de la creación, Génesis 2 cambia el enfoque al orden lógico, centrándose en el hombre. Aquí Dios se revela con su nombre personal, Yahweh (Jehová/el Señor), mostrando su cuidado íntimo y personal al satisfacer todas las necesidades del hombre: físicas, emocionales y espirituales.",
    gardenAndProvision: "Dios provee abundantemente para Adán en el Edén. En medio del jardín, coloca dos árboles significativos: el Árbol de la Vida y el Árbol de la Ciencia del Bien y del Mal. Este último no era intrínsecamente malo, sino que representaba una prueba fundamental: ¿Confiaría el hombre en la revelación de Dios o buscaría el conocimiento del bien y del mal por su propia experiencia, independiente de Dios? La obediencia manifestaría amor y dependencia; la desobediencia, lo contrario.",
    sabbathRest: "Dios descansa en el séptimo día y lo santifica. Este acto no se debe al cansancio, sino que establece un principio fundamental. El Sabbath se convierte en un símbolo del descanso final y la comunión eterna que el pueblo de Dios encontrará en Él (Hebreos 4). Cada séptimo día sería un recordatorio y un anticipo de esa esperanza celestial.",
    womanAndFamily: "Dios satisface la necesidad de compañía del hombre creando a la mujer como una 'ayuda idónea', hecha para completarlo. La creación de la mujer a partir del hombre, y el subsecuente nacimiento del hombre a través de la mujer, establece una profunda interdependencia. Así, Dios instituye la familia como la unidad fundamental a través de la cual su plan redentor se desarrollaría, una relación que reflejaría el misterio de Cristo y la Iglesia (Efesios 5).",
    fullText: chapter2FullText
};

export const FILL_IN_THE_BLANK_2 = {
    sentence: "El Árbol de la Ciencia del Bien y del Mal fue colocado en el jardín para probar, a través de la obediencia, el ___ que Adán le tenía a Dios.",
    correctAnswer: "amor"
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
    {
        question: "¿Cuáles son las tres cualidades esenciales del pueblo de Dios que se desarrollan a través del Antiguo Testamento?",
        options: ["Fe, Amor y Esperanza", "Obediencia, Sacrificio y Oración", "Justicia, Juicio y Misericordia", "Poder, Riqueza y Sabiduría"],
        correctAnswer: "Fe, Amor y Esperanza",
    },
    {
        question: "¿Qué representa el sistema de sacrificios en el Antiguo Testamento?",
        options: ["Una forma de ganar el favor de Dios", "Una tradición cultural sin significado profundo", "Un medio para humillar al pueblo, enseñarles a confiar en Dios y señalar la necesidad de un Salvador", "Un castigo por los pecados cometidos"],
        correctAnswer: "Un medio para humillar al pueblo, enseñarles a confiar en Dios y señalar la necesidad de un Salvador",
    },
    {
        question: "¿Cuál es el propósito de Dios al crear al hombre, según se cita de Efesios 1:4?",
        options: ["Que el hombre dominara la tierra", "Que el hombre fuera un siervo de Dios", "Que fuésemos santos y sin mancha delante de él, en amor", "Que el hombre construyera grandes civilizaciones"],
        correctAnswer: "Que fuésemos santos y sin mancha delante de él, en amor",
    },
];

const dragItems: DragItem[] = [
    { id: 'item-1', type: 'item', content: 'Amós' },
    { id: 'item-2', type: 'item', content: 'Oseas' },
    { id: 'item-3', type: 'item', content: 'Jeremías' },
];

const dropTargets: DropTarget[] = [
    { id: 'target-1', type: 'target', content: 'Describe la falta de amor del pueblo hacia Dios.', expectedId: 'item-2' },
    { id: 'target-2', type: 'target', content: 'Enfoca la condición pecadora de los corazones y la necesidad de un cambio.', expectedId: 'item-3' },
    { id: 'target-3', type: 'target', content: 'Reprende la falta de amor mutuo y la injusticia social.', expectedId: 'item-1' },
];

export const DRAG_DROP_ITEMS = { items: dragItems, targets: dropTargets };

export const TIMELINE_EVENTS: TimelineEventData[] = [
    { period: "Patriarcas", title: "Abraham, Isaac y Jacob", description: "Dios llama a un pueblo para sí y les da promesas fundamentales de una simiente (descendencia) y una herencia (la tierra)." },
    { period: "Éxodo y Ley", title: "Moisés en el Sinaí", description: "Liberación de la esclavitud en Egipto y entrega de la Ley, estableciendo el pacto de Dios y las bases para una nación santa." },
    { period: "Conquista y Jueces", title: "Josué y los Jueces", description: "Israel toma posesión de la Tierra Prometida, seguido por un trágico ciclo de desobediencia, opresión y liberación divina." },
    { period: "Reino Unido", title: "Saúl, David y Salomón", description: "El apogeo de Israel como nación, marcado por el liderazgo fiel (David) e infiel (Saúl) y la eventual decadencia iniciada por Salomón." },
    { period: "Reino Dividido y Profetas", title: "Isaías, Jeremías, Amós", description: "La nación se divide. Dios levanta profetas para llamar al pueblo al arrepentimiento ante la idolatría y la injusticia social." },
    { period: "Exilio y Retorno", title: "Ezequiel, Daniel, Esdras", description: "Juicio a través de la caída de Jerusalén y el cautiverio en Babilonia, seguido por el regreso de un remanente fiel para reconstruir el templo y los muros." },
];

export const CREATION_HOTSPOTS: Hotspot[] = [
    { id: 1, x: 15, y: 25, title: "Día 1: La Luz", description: "Dios separó la luz de las tinieblas. 'Y vio Dios que la luz era buena'." },
    { id: 2, x: 50, y: 15, title: "Día 2: El Firmamento", description: "Creó la expansión (cielos) para separar las aguas de arriba de las de abajo, preparando un espacio vital." },
    { id: 3, x: 80, y: 70, title: "Día 3: Tierra Seca y Plantas", description: "Separó las aguas de la tierra seca y ordenó que la tierra produjera vegetación." },
    { id: 4, x: 20, y: 80, title: "Día 4: Sol, Luna y Estrellas", description: "Creó las lumbreras en los cielos para señalar estaciones, días y años." },
    { id: 5, x: 65, y: 45, title: "Día 5: Criaturas Marinas y Aves", description: "Llenó las aguas con seres vivientes y los cielos con aves." },
    { id: 6, x: 45, y: 75, title: "Día 6: Animales y el Hombre", description: "Creó los animales terrestres y, como culminación, al hombre y la mujer a su propia imagen." },
    { id: 7, x: 85, y: 20, title: "Día 7: El Descanso", description: "Dios descansó de su obra, santificando el día como un recordatorio del propósito final de Dios y un anticipo de la eternidad con Él." },
];
